[tool.poetry]
name = "framework"
version = "0.3.0"
description = "custom async backend framework on sockets and without asyncio"
authors = ["mrtedn21 <bezgin.sasha06@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.1.1"
sqlalchemy = "^2.0.19"
asyncpg = "^0.28.0"
uvloop = "^0.17.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.287"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
