[tool.poetry]
name = "framework"
version = "0.2.0"
description = "custom async backend framework on sockets and without asyncio"
authors = ["mrtedn21 <bezgin.sasha06@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.19"
pydantic = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
