[tool.poetry]
name = "framework"
version = "0.3.0"
description = "custom async backend framework on sockets and without asyncio"
authors = ["mrtedn21 <bezgin.sasha06@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.1.1"
sqlalchemy = "^2.0.19"
asyncpg = "^0.28.0"
uvloop = "^0.17.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
flake8 = "^6.1.0"
flake8-async = "^22.11.14"
flake8-warnings = "^0.4.0"
flake8-commas = "^2.1.0"
flake8-comprehensions = "^3.14.0"
flake8-literal = "^1.3.0"
flake8-multiline-containers = "^0.0.19"
flake8-picky-parentheses = "^0.5.0"
flake8-quotes = "^3.3.2"
flake8-builtins = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
